log_level: INFO

backend: local
local-config:
  tmp_dir: /tmp

backup_directory: ./backup

mongo_opt:
  database: INGInious
  host: mongodb://db

superadmins:
- superadmin

tasks_directory: ./course-files

use_minified_js: true
maintenance: false

# smtp:
#   sendername: 'INGInious <inginious@doc.gold.ac.uk>'
#   host: 'smtp.office365.com'
#   port: 587
#   username: ''
#   password: ''
#   starttls: True

plugins:
- plugin_module: inginious.frontend.plugins.auth.ldap_auth
  host: "campus.goldsmiths.ac.uk"
  encryption: "none" #can be ssl, tls or none
  base_dn: "ou=goldsmiths_users,dc=campus,dc=goldsmiths,dc=ac,dc=uk"
  request: "sAMAccountName={}"
  prefix: ""
  name: "INGI Login"
  require_cert: false
