# TODO: Add SMTP service

version: '3.3'

services:
  db:
    image: mongo:latest
    volumes:
      - db_data:/data/db
    networks:
      - ingi_net

  inginious:
    image: inginious
    build:
      context: ./
      dockerfile: dockerfile
    image: inginious
    command: ["inginious-webapp", "--host", "0.0.0.0"]
    ports:
      - "8080:8080"             # host:container
    volumes:
      - tmp:/tmp/inginious      # sibling container communication
      - type: bind              # use local file system for backup
        source: ./backup
        target: /app/backup
      - type: bind              # make the host dockerd accessible
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    depends_on:
      - db
    networks:
      - ingi_net

volumes:
  db_data:
  tmp:

networks:
  ingi_net:
